INSERT INTO fabricante(id, nombre) VALUES (1, 'Asus');
INSERT INTO fabricante(id, nombre) VALUES (2, 'Dell');
INSERT INTO fabricante(id, nombre) VALUES (3, 'HP');
INSERT INTO fabricante(id, nombre) VALUES (4, 'Logitech');
INSERT INTO fabricante(id, nombre) VALUES (5, 'Corsair');
INSERT INTO fabricante(id, nombre) VALUES (6, 'Razer');
INSERT INTO fabricante(id, nombre) VALUES (7, 'Samsung');
INSERT INTO fabricante(id, nombre) VALUES (8, 'MSI');
INSERT INTO fabricante(id, nombre) VALUES (9, 'Gigabyte');
INSERT INTO fabricante(id, nombre) VALUES (10, 'Intel');

INSERT INTO producto (id, nombre, precio, id_fabricante) VALUES (1, 'Disco duro SATA3 1TB', 86.99, 5);
INSERT INTO producto (id, nombre, precio, id_fabricante) VALUES (2, 'Monitor LED 24 pulgadas', 149.99, 7);
INSERT INTO producto (id, nombre, precio, id_fabricante) VALUES (3, 'Teclado mecánico retroiluminado', 79.95, 6);
INSERT INTO producto (id, nombre, precio, id_fabricante) VALUES (4, 'Laptop ultrabook Core i7', 999.99, 2);
INSERT INTO producto (id, nombre, precio, id_fabricante) VALUES (5, 'Mouse inalámbrico gaming', 49.99, 4);
INSERT INTO producto (id, nombre, precio, id_fabricante) VALUES (6, 'Procesador Intel Core i9', 489.00, 10);
INSERT INTO producto (id, nombre, precio, id_fabricante) VALUES (7, 'Tarjeta gráfica RTX 4070', 799.00, 8);
INSERT INTO producto (id, nombre, precio, id_fabricante) VALUES (8, 'Memoria RAM DDR4 16GB', 99.50, 3);
INSERT INTO producto (id, nombre, precio, id_fabricante) VALUES (9, 'Placa base Z790', 239.99, 9);
INSERT INTO producto (id, nombre, precio, id_fabricante) VALUES (10, 'SSD NVMe 1TB', 129.00, 5);
INSERT INTO producto (id, nombre, precio, id_fabricante) VALUES (11, 'Fuente de poder 750W', 119.00, 9);
INSERT INTO producto (id, nombre, precio, id_fabricante) VALUES (12, 'Cámara web Full HD', 69.99, 4);
